### ISSUE TITLE
generator.js tmp dir Ubuntu 16 issue

### ISSUE THREAD

**Issue by titilo** [Menardi/vue-cli-plugin-cordova-simple#1]
Hi,

Line 23 in generator.js file is:

`const tmpDir = fs.mkdtempSync(os.tmpdir());`

On Ubuntu, os.tmpdir() returns '/tmp' without a trailing slash. Then node tries to write to '/' (for example, '/tmpJFfYxA')

Adding a slash to the path seems to solve the issue:

`const tmpDir = fs.mkdtempSync(os.tmpdir() + '/');`

A workaround I found is to change ownership of '/' to my user (don't know if this might cause me problems).

Thanks

**Comment by Menardi** [comment]
Apologies for the delay, I didn't notice this issue until today. I have fixed it, along with some other issues, and it is now on npm as version `1.0.1`. Thanks for the report!
